CREATE SCHEMA IF NOT EXISTS CC00770xMail DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;

USE CC00770xMail;
CREATE TABLE IF NOT EXISTS USERS (
username VARCHAR(100) NOT NULL,
userpassword VARCHAR(100) NOT NULL,
PRIMARY KEY (username))
COLLATE='utf8_bin'
ENGINE=InnoDB;

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234'